const page=document.body.dataset.page;document.querySelectorAll('.nav a').forEach(a=>{if(a.dataset.page===page)a.classList.add('active')});
window.addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){const group=b.closest('[data-tabs]');group.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const target=b.dataset.tab;document.querySelectorAll(`[data-panel-group="${group.dataset.tabs}"]`).forEach(p=>p.classList.toggle('active',p.id===target));}
const m=e.target.closest('[data-modal-open]');if(m)document.getElementById(m.dataset.modalOpen).classList.add('open');if(e.target.matches('[data-modal-close]')||e.target.classList.contains('modal'))e.target.closest('.modal')?.classList.remove('open');
const task=e.target.closest('[data-complete]');if(task){task.closest('tr')?.classList.add('completed');task.textContent='Completed';task.disabled=true;}
});
function openAI(){document.getElementById('ai').classList.add('open');document.querySelector('.fab').style.display='none'}function closeAI(){document.getElementById('ai').classList.remove('open');document.querySelector('.fab').style.display='block'}
const aiKnowledge=[
[/today|brief/i,'Today: 18 appointments, 3 patients with incomplete intake, 2 unsigned consents, 1 missing cardiac clearance, 4 billing items awaiting documentation, and 2 high-priority exceptions.'],
[/intake|forms/i,'Intake summary: Maria Lopez is pending staff review; Daniel Reed is missing an insurance card; Helen Wu has a positive anesthesia-history response requiring clinician review.'],
[/billing|claim|denial/i,'Billing summary: $24,850 collected this week. 7 claims are not ready, 4 are denied, and 2 may be underpaid. Highest-priority denial is Claim 10428 with a 6-day appeal window.'],
[/patient|maria/i,'Maria Lopez: DOB 04/18/1978. New surgical consult. Latex allergy. Intake 88% complete. Missing anesthesia signature. Balance due: $175.'],
[/schedule|slot|appointment/i,'Suggested opening: Tuesday 2:30 PM with Dr. Shah in Procedure Room 2 for a 30-minute follow-up. No resource conflict detected. Staff approval is required before booking.'],
[/renewal|license|credential/i,'Administrative alert: Dr. Shah’s DEA registration expires in 42 days. Cyber liability policy renewal is due in 61 days.'],
[/help|commands/i,'Try: “daily brief,” “intake exceptions,” “billing summary,” “find Maria,” “suggest a follow-up slot,” or “upcoming renewals.”']
];
function sendAI(){const input=document.getElementById('aiInput');const text=input.value.trim();if(!text)return;const body=document.getElementById('aiBody');body.insertAdjacentHTML('beforeend',`<div class="msg user">${text.replace(/[<>]/g,'')}</div>`);let response='I can simulate operational support using the sample data in this prototype. I will not finalize clinical, billing, identity, consent, or privacy-sensitive changes without human review.';for(const [re,ans] of aiKnowledge){if(re.test(text)){response=ans;break}}setTimeout(()=>{body.insertAdjacentHTML('beforeend',`<div class="msg bot">${response}</div>`);body.scrollTop=body.scrollHeight},220);input.value=''}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('aiSend')?.addEventListener('click',sendAI);document.getElementById('aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendAI()});document.querySelectorAll('[data-filter]').forEach(sel=>sel.addEventListener('change',()=>{const val=sel.value;document.querySelectorAll(sel.dataset.filter).forEach(el=>el.style.display=(val==='all'||el.dataset.status===val)?'':'none')}));});
